name: Deploy to GCP

on:
  push:
    branches:
      - master  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get vm ip
      run: echo "${{ secrets.GCP_VM_IP }}"
    - name: Get vm user
      run: echo "${{ secrets.GCP_VM_USER }}"
    - name: Deploy to GCP VM via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        port: 22

        script: |
          cd /kocart
          git pull origin master
          npm install
          npm run build
          pm2 restart all
